/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.projeto.saude.tela.tecnico;

import br.com.projeto.saude.controller.ControllerConsulta;
import br.com.projeto.saude.controller.ControllerPaciente;
import br.com.projeto.saude.model.Consulta;
import br.com.projeto.saude.model.Paciente;
import br.com.projeto.saude.model.Tecnico;
import br.com.projeto.saude.tela.consulta.AtualizarConsulta;
import br.com.projeto.saude.tela.consulta.SolicitarConsultaEmergencia;
import br.com.projeto.saude.tela.medico.CadastrarMedico;
import java.util.List;

/**
 *
 * @author tecin
 */
public class MainTecnico extends javax.swing.JFrame {

    private ControllerPaciente controllerPaciente;
    private ControllerConsulta controllerConsulta;
    private Tecnico tecnico;
    private List<Paciente> pacientes;
    private List<Consulta> consultas;
    
    /**
     * Creates new form MainTecnico
     */
    public MainTecnico() {
        initComponents();
    }
    
    public MainTecnico(Tecnico tecnico){
        initComponents();
        this.controllerPaciente = new ControllerPaciente();
        this.controllerConsulta = new ControllerConsulta();
        this.tecnico = tecnico;
        listarPacientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        bt_cadastrarMedico = new javax.swing.JButton();
        bt_solicitarConsultaEmergencia = new javax.swing.JButton();
        bt_atualizarConsulta = new javax.swing.JButton();
        cb_paciente = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb_consulta = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ÁREA DO TECNICO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        bt_cadastrarMedico.setText("CADASTRAR MEDICO");
        bt_cadastrarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrarMedicoActionPerformed(evt);
            }
        });

        bt_solicitarConsultaEmergencia.setText("SOLICITAR CONSULTA EMERGENCIA");
        bt_solicitarConsultaEmergencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_solicitarConsultaEmergenciaActionPerformed(evt);
            }
        });

        bt_atualizarConsulta.setText("ATUALIZAR CONSULTA");
        bt_atualizarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_atualizarConsultaActionPerformed(evt);
            }
        });

        cb_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_pacienteActionPerformed(evt);
            }
        });

        jLabel1.setText("PACIENTE");

        jLabel2.setText("CONSULTA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_paciente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cb_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bt_cadastrarMedico)
                        .addGap(18, 18, 18)
                        .addComponent(bt_solicitarConsultaEmergencia))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(bt_atualizarConsulta)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_cadastrarMedico)
                    .addComponent(bt_solicitarConsultaEmergencia))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_atualizarConsulta)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_atualizarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_atualizarConsultaActionPerformed
        AtualizarConsulta atualizarConsulta = new AtualizarConsulta(this.consultas.get(cb_consulta.getSelectedIndex()));
        atualizarConsulta.setVisible(true);
    }//GEN-LAST:event_bt_atualizarConsultaActionPerformed

    private void bt_cadastrarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrarMedicoActionPerformed
        CadastrarMedico cadastrarMedico = new CadastrarMedico(this.tecnico);
        cadastrarMedico.setVisible(true);
    }//GEN-LAST:event_bt_cadastrarMedicoActionPerformed

    private void bt_solicitarConsultaEmergenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_solicitarConsultaEmergenciaActionPerformed
        SolicitarConsultaEmergencia solicitarConsultaEmergencia = new SolicitarConsultaEmergencia();
        solicitarConsultaEmergencia.setVisible(true);
    }//GEN-LAST:event_bt_solicitarConsultaEmergenciaActionPerformed

    private void cb_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_pacienteActionPerformed
        cb_consulta.removeAllItems();
        listarConsultas();
    }//GEN-LAST:event_cb_pacienteActionPerformed

    private void listarPacientes(){
        this.pacientes = this.controllerPaciente.listar();
        pacientes.stream()
                .forEach(paciente -> cb_paciente.addItem(paciente.getCpf()));
    }
    
    private void listarConsultas(){
        this.consultas = this.controllerConsulta.listar(this.pacientes.get(cb_paciente.getSelectedIndex()));
        consultas.stream()
                .forEach(consulta -> cb_consulta.addItem(consulta.getMedico().getCrm() + " - " + consulta.getDataRealizacao()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainTecnico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_atualizarConsulta;
    private javax.swing.JButton bt_cadastrarMedico;
    private javax.swing.JButton bt_solicitarConsultaEmergencia;
    private javax.swing.JComboBox<String> cb_consulta;
    private javax.swing.JComboBox<String> cb_paciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
